# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(default=None, max_length=150)),
                ('aadhaar_id', models.CharField(default=None, max_length=12)),
                ('m_id', models.IntegerField(default=0)),
                ('name_hnd', models.CharField(default=None, max_length=150)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('dob', models.DateField(default=None, null=True)),
                ('hof', models.BooleanField(default=False)),
                ('family_id', models.CharField(default='', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
