# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lochof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lochof',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
